apiVersion: v1
kind: Service
metadata:
  name: example-app-1
  namespace: default
  labels:
    app: example-app-1
spec:
  type: ClusterIP
  selector:
    app: example-app-1
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000